/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package ${basePackage}.service;

import java.util.List;
import java.util.Optional;
import ${basePackage}.model.${modelName};
import ${derivedServiceRef};
import ${pageRef};
import ${pageParamRef};

/**
 * “${modelCn}”业务
${classDocEnd}
public interface ${modelName}Service extends ${derivedServiceName}<${modelName}> {

    Long createEX(${modelName} ${modelName?uncap_first});

    ${modelName} getEX(Long id);

    void updateEX(${modelName} ${modelName?uncap_first});

    void deleteEX(Long id);

    String deleteEX(List<Long> ids);

    Page<${modelName}> page(PageParam pageParam);

}